---
apiVersion: v1
kind: Service
metadata:
  name: rest-backend
spec:
  selector:
    app: rest-backend
  ports:
  - port: 7001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: rest-backend
    spec:
      containers:
      - name: rest-backend
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=7001"
        - "--response-text=rest-backend"
        ports:
        - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-backend
spec:
  selector:
    app: grpc-backend
  ports:
  - port: 7002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: grpc-backend
    spec:
      containers:
      - name: grpc-backend
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--grpc-server-port=7002"
        - "--response-text=grpc-backend"
        ports:
        - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: buoyantio/bb:v0.0.5
        args:
        - broadcast-channel
        - "--h1-server-port=7000"
        - "--h1-downstream-server=http://rest-backend:7001"
        - "--grpc-downstream-server=grpc-backend:7002"
        ports:
        - containerPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.2.0
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          sleep 15 # wait for pods to start
          slow_cooker -qps=4 -concurrency=15 -interval=5s http://gateway:7000
